middleware:
  - selva.web.middleware.files.static_files_middleware
  - selva.web.middleware.files.uploaded_files_middleware
staticfiles:
  mappings:
#    /: index.html
    favicon.ico: python.ico

logging:
  format: console