site_name: Selva
site_description: Selva, elegant web framework
site_url: https://livioribeiro.github.io/selva/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select

repo_name: livioribeiro/selva
repo_url: https://github.com/livioribeiro/selva
edit_uri: ''

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Selva: index.md
  - tutorial.md
  - controllers.md
  - routing.md
  - templates.md
  - configuration.md
  - logging.md
  - Middleware:
    - Overview: middleware/overview.md
    - middleware/staticfiles_uploads.md
  - Extensions:
    - Overview: extensions/overview.md
    - extensions/sqlalchemy.md
    - extensions/redis.md
    - extensions/jinja.md
