[tool.poetry]
name = "dependency_injector"
version = "0.1.0"
description = "IoC Container"
authors = ["Livio Ribeiro <livioribeiro@outlook.com>"]
license = "MIT"
packages = [
    { include = "dependency_injector", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
mypy = "^0.942"
ward = "^0.65.0b0"
coverage = {version = "^6.3.2", extras = ["toml"]}

[tool.ward]
path = ["tests"]

[tool.coverage.run]
source = "src/dependency_injector"

[tool.pylint.MASTER]
disable = "C0114,C0115,C0116" # ignore missing docstrings

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
