[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "selva"
version = "0.1.0"
description = "Web Framework, IoC Container"
authors = ["Livio Ribeiro <livioribeiro@outlook.com>"]
license = "MIT"
packages = [
    { include = "selva", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.10"
asgikit = { path = "../asgikit", develop = true }

[tool.poetry.dev-dependencies]
uvicorn = {version = "^0.17.6", extras = ["standard"]}
pytest = "^7.1.2"
pytest-asyncio = "^0.18.3"
coverage = {version = "^6.4", extras = ["toml"]}
pylint = "^2.13.9"
black = "^22.3.0"
isort = "^5.10.1"
flake8 = "^4.0.1"
mypy = "^0.960"

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = [
    "tests",
]

[tool.coverage.run]
source = ["src"]

[tool.pylint.MASTER]
disable = ["C0114", "C0115", "C0116"] # ignore missing docstrings

[tool.mypy]
ignore_missing_imports = true
