[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "selva"
version = "0.6.7"
description = "ASGI Web Framework with Dependency Injection"
authors = ["Livio Ribeiro <livioribeiro@outlook.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/livioribeiro/selva"
keywords = ["asgi", "framework", "asyncio", "web"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Framework :: AsyncIO",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
]
packages = [
    { include = "selva", from = "src" },
    { include = "selva/py.typed", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.11"
starlette = "^0.26.1"
pydantic = "^1.10.7"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
uvicorn = { version = "^0.21.1", extras = ["standard"] }

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^7.2"
pytest-asyncio = "^0.21"
pytest-cov = "^4.0"
coverage = { version = "^7.2", extras = ["toml"] }

[tool.poetry.group.lint]
optional = true

[tool.poetry.group.lint.dependencies]
pylint = "^2.17"
black = "^23.1"
isort = "^5.12"
flake8 = "^6.0"
mypy = "^1.1"
ruff = "0.0.259"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
mkdocs-material = "^9.1.1"

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = [
    "tests",
]

[tool.coverage.run]
source = ["src"]

[tool.pylint.MASTER]
disable = ["C0114", "C0115", "C0116"] # ignore missing docstrings

[tool.mypy]
ignore_missing_imports = true

[tool.black]
line-length = 88
target-version = ['py310']
extend-exclude = "^/tests/configuration/invalid_settings/configuration/settings\\.py"
