[tool.poetry]
name = "dependency_injector"
version = "0.1.0"
description = "IoC Container"
authors = ["Livio Ribeiro <livioribeiro@outlook.com>"]
license = "MIT"
packages = [
    { include = "dependency_injector", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
isort = "^5.9.3"
flake8 = "^3.9.2"
mypy = "^0.910"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
pytest-asyncio = "^0.15.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
