auth:
  username: admin
  password: "123"

middleware:
  - application.middleware.auth_middleware
  - application.middleware.timing_middleware
  - application.middleware.logging_middleware

logging:
  root: WARNING
  level:
    application: INFO
    selva: INFO
  format: console
