middleware:
  - application.middleware.TimingMiddleware
  - application.middleware.LoggingMiddleware
  - application.middleware.AuthMiddleware

logging:
  root: WARNING
  level:
    application: INFO
    selva: INFO
