middleware:
  - application.middleware.timing_middleware
  - application.middleware.logging_middleware
  - application.middleware.auth_middleware

logging:
  root: WARNING
  level:
    application: INFO
    selva: INFO
  format: console
