data:
  sqlalchemy:
    default:
#      url: "sqlite+aiosqlite:///:memory:"
      drivername: sqlite+aiosqlite
#      username:
#      password:
#      host:
#      port:
      database: ":memory:"
#      query:
    other:
      url: "postgresql+asyncpg://localhost:5432/teste"
      username: postgres
      password: postgres
      params:
        pool_recycle: 3600
        echo: true