name: docs

on:
  push:
    branches:
      - main
    paths:
      - mkdocs.yml
      - 'docs/**'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.x
      - run: pdm install --with docs
      - run: pdm run mkdocs gh-deploy --force
