name: publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - run: pip install pipx
      - run: pipx install poetry
      - run: poetry build
      - shell: bash
        run: poetry config pypi-token.pypi "$PYPI_TOKEN" && poetry publish
        env:
          PYPI_TOKEN: "${secrets.PYPI_TOKEN}"
