name: test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "3.12"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}
      - run: pip install pipx
      - run: pipx install poetry
      - run: poetry install --with test --no-interaction
      - run: poetry run pytest
