name: test

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yml
      - pyproject.toml
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches:
      - main

env:
  POSTGRES_DB: test_db

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.11", "3.12"]
    container: python:${{ matrix.version }}
    services:
      postgres:
        image: postgres:16.1-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - run: pip install pipx && pipx install poetry
      - run: pip install asyncpg
      - run: poetry install --with test --extras jinja --extras sqlalchemy --no-interaction
      - env:
          POSTGRES_URL: postgresql+asyncpg://postgres:postgres@postgres:5342/${{ env.POSTGRES_DB }}
        run: poetry run pytest
