name: test

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yml
      - pyproject.toml
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.11", "3.12"]
    container: python:${{ matrix.version }}
    services:
      postgres:
        image: postgres:16.1-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: bitnami/redis:7.2.4
        env:
          REDIS_PASSWORD: password
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      memcached:
        image: memcached:1.6.23-alpine
        options: >-
          --health-cmd "echo 'stats' | nc 127.0.0.1 11211"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - run: pip install poetry
      - run: poetry install
          --with test
          --extras jinja
          --extras sqlalchemy
          --extras redis
          --extras memcached
          --no-interaction
      - env:
          POSTGRES_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/test
          REDIS_URL: redis://default:password@redis:6379/0
          MEMCACHED_ADDR: memcached:11211
        run: poetry run pytest
