name: test

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yml
      - pyproject.toml
      - 'src/**'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
      - run: pip install pipx
      - run: pipx install poetry
      - run: poetry install --with test --extras jinja,sqlalchemy --no-interaction
      - run: poetry run pytest
